import Head from 'next/head'
import Home from "../components/Home";
import requests from "../helpers/request";

export default function HomePage({movies}) {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Home movies={movies} />
    </div>
  )
}

export const getServerSideProps = async (context) => {
    const genre = context.query.genre;

    const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
    const movies = await request.json();

    return {
        props: {movies: movies.results}
    }
}
